### ISSUE TITLE
Use stdlib context on Go 1.7+

### ISSUE THREAD

**Issue by andrestc** [gorilla/pat#15]
Currently, `gorilla/pat` relies on `gorilla/context`, but since Go 1.7 that is actually not needed. I would like to propose that for Go 1.7+, `gorilla/pat` should use the native `context` package, just like `gorilla/mux` did: https://github.com/gorilla/mux/blob/master/context_native.go

The problem is that `gorilla/pat` would rely only on the `contextClear` func, that currently is a no-op on the native implementation. We could implement `contextClear` to set the request context as a fresh `context.Backgroun()`.

Would a PR for this be acceptable?

**Comment by elithrar** [comment]
Sure. We did a similar thing with mux - note that there's a need to
maintain backwards compat. with < Go 1.7 (as mux does).

gorilla/pat is effectively in maintenance mode otherwise.

**Comment by elithrar** [comment]
Going to close this out (timed out) - best to use https://github.com/gorilla/mux going forward.
