### ISSUE TITLE
Getting a Pat subrouter

### ISSUE THREAD

**Issue by arnaudbriche** [gorilla/pat#3]
Hi,

I use a mux.Router to handle top level path handling in my app,
and I'd like to use pat.Router for second-level path handling.
So I'd like to get a pat.Router as subrouter of a mux.Router.

Something like : 

    r := mux.NewRouter()
    articles.Register(r.PathPrefix("/articles").Subrouter())

And in articles package: 

    func Register(r *pat.Router) {
        r.Get("/{id}", read)    
    }

**Comment by elithrar** [comment]
I'm going to close this one out due to lack of activity (sorry that no one replied!).
