### ISSUE TITLE
Implement HTTP PATCH

### ISSUE THREAD

**Issue by dobegor** [gorilla/pat#8]
In REST-like API, PUT should only be used if you're replacing a resource in it's entirety.

According to RFC 5789:
> Several applications extending the Hypertext Transfer Protocol (HTTP) require a feature to do partial resource modification. The existing HTTP PUT method only allows a complete replacement of a document. This proposal adds a new HTTP method, PATCH, to modify an existing HTTP resource.

**Comment by elithrar** [comment]
Note that `pat` doesn't see a lot of love, but I'd happily accept a PR for this.

Otherwise, I'd recommend using [https://godoc.org/github.com/gorilla/mux#Route.Methods](gorilla/mux) or [muxy](https://godoc.org/github.com/gorilla/muxy#Route.Patch) which are more flexible around method handling.

**Comment by dobegor** [comment]
@elithrar 
I don't think I have enough experience yet in Golang to submit a PR like this, but I think this issue should be open if someone else cares.
Thanks anyway :smile:

**Comment by elithrar** [comment]
@dobegor See https://github.com/gorilla/pat/pull/9 for how I did this (it was a simple copy+paste in this instance).

Run `go get -u github.com/gorilla/pat` to fetch the latest version :)

**Comment by dobegor** [comment]
@elithrar LGTM. Thanks!
